version: '3.8'

services:
  adminer:
    build:
      context: ./adminer
    ports:
      - "8080:8080"

  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  composer:
    image: custom/composer
    build:
      context: ./composer
    volumes:
      - ./symfony:/app

  symfony:
    build:
      context: ./symfony
    ports:
      - "8000:8000"
    volumes:
      - ./symfony:/app
    depends_on:
      - postgres
      - composer

volumes:
  postgres_data: {}

