version: '3.8'

services:
  adminer:
    build:
      context: ./adminer
    ports:
      - "8080:8080"

  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: skytowers_explorer_db
      POSTGRES_USER: skyexplorer_user
      POSTGRES_PASSWORD: strong_password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  composer:
    image: custom/composer
    build:
      context: ./composer
    volumes:
      - ./symfony/SkyTowersExplorer:/app

  symfony:
    build:
      context: ./symfony
    ports:
      - "8000:8000"
    volumes:
      - ./symfony/SkyTowersExplorer:/app
    depends_on:
      - postgres
      - composer
    command: >
      sh -c '
      composer install --no-interaction --no-scripts &&
      sleep 10 &&
      php bin/console doctrine:database:create --if-not-exists &&
      php bin/console doctrine:migrations:migrate --no-interaction &&
      php bin/console doctrine:fixtures:load --no-interaction &&
      php bin/console cache:clear --no-warmup &&
      php8 -S 0.0.0.0:8000 -t /app/public'

volumes:
  postgres_data: {}

